[package]
name = "goodmetrics_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log =  { version = "0.4" }

[build-dependencies]
tonic-build = { version = "0.8.0", features = [] }

[dev-dependencies]
env_logger = { version = "0.9.3" }
test-log = { version = "0.2.11" }
