[package]
name = "goodmetrics_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log =  { version = "0.4" }

futures = { version = "0.3" }
futures-batch = { version = "0.6" }
futures-timer = { version = "3.0" }

tonic = { version = "0.8", features = ["tls"] }
prost = { version = "0.11" }
hyper = { version = "0.14" }
tower = { version = "0.4" }
tokio-rustls = { version = "*", features = ["dangerous_configuration"] }
hyper-rustls = { version = "0.23", features = ["http2"] }

[build-dependencies]
tonic-build = { version = "0.8", features = [] }

[dev-dependencies]
env_logger = { version = "0.9" }
test-log = { version = "0.2" }
tokio = { version = "1.21" }
tokio-test = { version = "0.4" }
