name: PR

on:
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Rustfmt
      run: cargo fmt -- --check
    - name: Clippy
      run: |
        cargo --version
        cargo clippy --version
        cargo clippy --all-targets --all-features -- -D warnings
    - name: Run tests
      run: cargo test --verbose
